### ISSUE TITLE
Why static files partially come?

### ISSUE THREAD

**Issue by elcolie** [py-pa/django-minio-storage#29] opened 2017-06-20 08:57 UTC
https://cl.ly/323p1z151Z3i
https://cl.ly/1H2q2c012K2J
I have them in directory.
```bash
(eneos-factory) root@eneos-factory-dev:~/eneos-factory# ls static/rest_framework/img/
glyphicons-halflings.png  glyphicons-halflings-white.png  grid.png
```

django-minio-storage==0.1.0
minio==2.2.1              # via django-minio-storage
django==1.11

**settings.py**:
```python
DEFAULT_FILE_STORAGE = "minio_storage.storage.MinioMediaStorage"
STATICFILES_STORAGE = "minio_storage.storage.MinioStaticStorage"

MINIO_STORAGE_ENDPOINT = "eneos-factory.c0d1um.io"
MINIO_STORAGE_ACCESS_KEY = "KBP6WXGPS387090EZMG8"
MINIO_STORAGE_SECRET_KEY = "DRjFXylyfMqn2zilAr33xORhaYz5r9e8r37XPz3A"
MINIO_STORAGE_USE_HTTPS = True

MINIO_STORAGE_MEDIA_BUCKET_NAME = "media"
MINIO_STORAGE_AUTO_CREATE_MEDIA_BUCKET = True
MINIO_STORAGE_STATIC_BUCKET_NAME = "static"
MINIO_STORAGE_AUTO_CREATE_STATIC_BUCKET = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'

# Media configuration
MEDIA_URL = '/media/'

# Proxy server settings: Hey, Django, whenever you get an "X_Forwarded_Proto" in the HTTP request,
# it means a HTTPS request was sent to the proxy server by the end users
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
```

**site-enable:**
```bash
upstream app {
  server localhost:8000;
}
upstream minio {
  server localhost:9000;
}

server {
  listen 80;
  server_name eneos-factory.c0d1um.io;
  return 301 https://$server_name$request_uri;
}

server {
    listen 443 ssl;
    server_name eneos-factory.c0d1um.io;

    add_header Strict-Transport-Security "max-age=31536000";
    ssl_certificate /etc/letsencrypt/live/eneos-factory.c0d1um.io/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/eneos-factory.c0d1um.io/privkey.pem;

    location / {
            proxy_pass_request_headers on;
            proxy_set_header           Host $host;
            proxy_pass                 http://app;
    }

    location /static {
        proxy_buffering off;
        proxy_set_header Host $http_host;
        proxy_pass http://minio;
    }

   location /media {
   	    proxy_buffering off;
        proxy_set_header Host $http_host;
        proxy_pass http://minio;
    }

    location ~ /.well-known {
                allow all;
    }
}
```

Where am I wrong?

**Comment by thomasf** [comment] 2017-06-20 09:25
Probably access rights issues..

URLs which are created by Django are signed so that read access is granted by
minio, if those files have links in them to other static files they won't be
signed and then won't load.

**Comment by thomasf** [comment] 2017-06-20 09:32
You can try out this version (also on pypi under a different name) https://github.com/py-pa/django-minio-storage which among other things have options to turn url signing on/off  but be aware that it will be removed from pypi later on and merged into this repository again. (You also need to add read access bucket ACL in minio)

**Comment by elcolie** [comment] 2017-06-20 09:53
I have uninstalled the `django-minio-storage`. And change `requirements.txt`
```bash
#django-minio-storage==0.1.0
-e git://github.com:py-pa/django-minio-storage.git
```
```bash
Obtaining master from git+git://github.com:py-pa/django-minio-storage.git#egg=master (from -r requirements.txt (line 26))
  Cloning git://github.com:py-pa/django-minio-storage.git to /root/.pyenv/versions/3.6.1/envs/eneos-factory/src/master
fatal: unable to connect to github.com:py-pa:
github.com:py-pa: Name or service not known

Command "git clone -q git://github.com:py-pa/django-minio-storage.git /root/.pyenv/versions/3.6.1/envs/eneos-factory/src/master" failed with error code 128 in None
```

**Comment by thomasf** [comment] 2017-06-20 09:55
use `django-minio-storage-py-pa==0.0.2` instead..

**Comment by elcolie** [comment] 2017-06-20 10:02
```bash
(eneos-factory) root@eneos-factory-dev:~/eneos-factory# python manage.py collectstatic --settings=factory.config.settings.dev
Hey, I'm DEV!
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/root/.pyenv/versions/eneos-factory/lib/python3.6/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/root/.pyenv/versions/eneos-factory/lib/python3.6/site-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/root/.pyenv/versions/eneos-factory/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/root/.pyenv/versions/eneos-factory/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/root/.pyenv/versions/eneos-factory/lib/python3.6/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 173, in handle
    if self.is_local_storage() and self.storage.location:
  File "/root/.pyenv/versions/eneos-factory/lib/python3.6/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 227, in is_local_storage
    return isinstance(self.storage, FileSystemStorage)
  File "/root/.pyenv/versions/eneos-factory/lib/python3.6/site-packages/django/utils/functional.py", line 238, in inner
    self._setup()
  File "/root/.pyenv/versions/eneos-factory/lib/python3.6/site-packages/django/contrib/staticfiles/storage.py", line 504, in _setup
    self._wrapped = get_storage_class(settings.STATICFILES_STORAGE)()
  File "/root/.pyenv/versions/eneos-factory/lib/python3.6/site-packages/django/core/files/storage.py", line 467, in get_storage_class
    return import_string(import_path or settings.DEFAULT_FILE_STORAGE)
  File "/root/.pyenv/versions/eneos-factory/lib/python3.6/site-packages/django/utils/module_loading.py", line 20, in import_string
    module = import_module(module_path)
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/root/.pyenv/versions/eneos-factory/lib/python3.6/site-packages/minio_storage/storage.py", line 13, in <module>
    from minio.error import NoSuchBucket, NoSuchKey, ResponseError
ImportError: cannot import name 'NoSuchBucket'
```
???

**Comment by elcolie** [comment] 2017-06-20 10:05
https://cl.ly/400N1x0K0h01

**Comment by thomasf** [comment] 2017-06-20 10:14
Ok. There are probably still a couple of problems relating to staticfiles storage, media storage is currently a bit more solid until we decided upon some error handling stuff.

The error you are getting are strange since NoSuchBucket is in minio.error 
( https://github.com/minio/minio-py/blob/master/minio/error.py#L452 )

**Comment by elcolie** [comment] 2017-06-20 10:16
Thomasf. Thank you for your time. I will wait the official release on this issue.
Currently it is not a big deal on production server. And I think I can workaround in the Django Admin Page using `django-suit`.

**Comment by elcolie** [comment] 2017-06-21 16:59
Please let me know when `django-minio-storage` can handle this issue. `django-suit` also has the same problem because in the render time it use simple static URL not a minio encrypted URL

**Comment by thomasf** [comment] 2017-06-21 17:16
I'll try to remember to ping you when this changes but I can't make any guarantees

**Comment by Yurmusp** [comment] 2017-06-30 20:53
I can confirm static files have issues. I was not able to make them work right away and just gave up for now. For now I have minio used only for media files.
Also, I think for static if there are references inside some minio files, then access to static bucket shall be anonymous and without signature. Otherwise, such transitional references can not really work I think. Probably, can be easier to serve then static files via nginx or some other server. I just remained on FileSystemStorage for statics.

**Comment by thomasf** [comment] 2017-07-16 10:20
We should definitley have a collectstatic test along with the fix

**Comment by Yurmusp** [comment] 2017-07-17 20:54
static files requires this folder_exists thing to work. Otherwise it fails on checking folder. there is dirty commit from me somewhere but it shall be done in more complete way with tests.

**Comment by thomasf** [comment] 2017-09-19 18:48
should be fixed by now. In part earlier and in part in 67e6be7c6d7031f35fd8a4b65a9d58cc8cc2d105

**Closed as completed by thomasf** 2017-09-19 18:48 UTC
Labels: bug
